### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by RichardPaulAstley** [Galleom/PokeChecker#1]
Hi ! 
I discovered your project today, and I'm a huge huge fan. I'm dealing with Pokemon collections, many data and this is like the most complete tool I've found since a long long long time.

However, i've two suggestions : 

- Could it be possible to add a forms in the Others setting ? That way you could opt out forms in the case you want ONE kind of Pokemon and not all forms.
- Could it be possible to export the results to a .csv file ? Like just the number + name. Something simple to be able to export to other files like excel etc ? Could help a LOT collection trackers.

Thanks for your work and your time on it

**Comment by Galleom** [comment]
Hey, thank you!

Yeah I was needing a tool for some specific ribbon projects which is why I did this, haha

Adding a forms option sounds a good idea. I'll have to add this by hand but, shouldn't be too difficult. Most forms (like all the rotom formes) are already compressed to their base form, but sounds useful for things like regional forms 

FYI, I've made the csv files available in this repo: https://github.com/Galleom/PokeSprite-Helper

However, exporting as a standalone does sound useful and short search indicates exporting is possible, so I'll probably add it as well.

**Comment by Galleom** [comment]
Alright, added both features: Now there's the "forms" option as well as the csv exporting button.

The button is a repeat ball under the pokemon counter.

**Comment by RichardPaulAstley** [comment]
Thanks a lot for this update ! 
I'm reopening that because I see a little issue to handle with the forms part. It should more remove anything that is dupe as forms ? Let me take an example.

I set up a Legends Arceus Living Dex info. I don't want duplicate forms to show up (for example, Typhlosion + H. Typhlosion) but by filtering out the forms, the Pokemon is simply gone : 

![image](https://github.com/user-attachments/assets/291a6fcc-7aff-49aa-8afe-9257a77adeb6)

Anything to make it more "only one pokemon of a kind" filter in that case ?
Thanks !

**Comment by Galleom** [comment]
Hmm it shouldn't remove dupes but it seems like the issue is that regular Typhlosion isn't compatible with PLA so without H!Typhlosion there isn't any Typhlosion to show in first place.

Selecting all gens and removing forms lists 1024 which is the correct id for terapagos, so I think it's displaying correctly?
